version: "3.9"
services:
  frontend:
    image: 488617992296.dkr.ecr.us-east-1.amazonaws.com/frontend:0.0.15
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - users
    - login
  users:
    image: 488617992296.dkr.ecr.us-east-1.amazonaws.com/users:0.0.3
    container_name: users
  login:
    image: 488617992296.dkr.ecr.us-east-1.amazonaws.com/login:0.0.8
    container_name: login
    depends_on:
    - users
    environment:
      USERS_API_ADDRESS: "users:80"
  todo:
    image: 488617992296.dkr.ecr.us-east-1.amazonaws.com/todo:0.0.2
    container_name: todo
    depends_on:
    - redis
  redis:
    container_name: redis
    image: redis